export const typographyTheme = {
  fontStacks: {
    heading: 'Oswald, sans-serif',
    body:
      '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol"',
    monospace: 'monospace',
  },

  fontStyles: {
    display: {
      fontSizeMin: '2.063rem',
      fontSizeMax: '2.25rem',
      fluidFontSize: '1.5vw + 1.563rem',
      lineHeightMin: '1.212',
      lineHeightMax: '1.194',
      fontStack: 'heading',
      fontWeight: '900',
      textDecoration: 'none',
      fontStyle: 'normal',
    },
    heading1: {
      fontSizeMin: '1.688rem',
      fontSizeMax: '1.875rem',
      fluidFontSize: '1.5vw + 1.188rem',
      lineHeightMin: '1.222em',
      lineHeightMax: '1.233em',
      fluidLineHeight: '1.722em - 1.5vw',
      fontStack: 'heading',
      fontWeight: '700',
      textDecoration: 'none',
      fontStyle: 'normal',
    },
    heading2: {
      fontSizeMin: '1.313rem',
      fontSizeMax: '1.5rem',
      fluidFontSize: '1.5vw + 0.813rem',
      lineHeightMin: '1.238',
      lineHeightMax: '1.25',
      fluidLineHeight: '1.738em - 1.5vw',
      fontStack: 'heading',
      fontWeight: '700',
      textDecoration: 'none',
      fontStyle: 'normal',
    },
    heading3: {
      fontSizeMin: '1.188rem',
      fontSizeMax: '1.375rem',
      fluidFontSize: '1.5vw + 0.688rem',
      lineHeightMin: '1.263',
      lineHeightMax: '1.273',
      fluidLineHeight: '1.763em - 1.5vw',
      fontStack: 'heading',
      fontWeight: '700',
      textDecoration: 'none',
      fontStyle: 'normal',
    },
    subtitle: {
      fontSizeMin: '1.125rem',
      fontSizeMax: '1.125rem',
      fluidFontSize: '1.5vw + 0.625rem',
      lineHeightMin: '1.44',
      lineHeightMax: '1.44',
      fluidLineHeight: '1.94em - 1.5vw',
      fontStack: 'body',
      fontWeight: '400',
      textDecoration: 'none',
      fontStyle: 'normal',
    },
    subtitle2: {
      fontSizeMin: '1.125rem',
      fontSizeMax: '1.125rem',
      fluidFontSize: '1.5vw + 0.625rem',
      lineHeightMin: '1.44',
      lineHeightMax: '1.44',
      fluidLineHeight: '1.94em - 1.5vw',
      fontStack: 'body',
      fontWeight: '700',
      textDecoration: 'none',
      fontStyle: 'normal',
    },
    body: {
      fontSizeMin: '1rem',
      fontSizeMax: '1rem',
      fluidFontSize: '1.5vw + 0.5rem',
      lineHeightMin: '1.5',
      lineHeightMax: '1.5',
      fluidLineHeight: '2em - 1.5vw',
      fontStack: 'body',
      fontWeight: '400',
      textDecoration: 'none',
      fontStyle: 'normal',
    },
    body2: {
      fontSizeMin: '1rem',
      fontSizeMax: '1rem',
      fluidFontSize: '1.5vw + 0.5rem',
      lineHeightMin: '1.5',
      lineHeightMax: '1.5',
      fluidLineHeight: '2em - 1.5vw',
      fontStack: 'body',
      fontWeight: '600',
      textDecoration: 'none',
      fontStyle: 'normal',
    },
    callout: {
      fontSizeMin: '0.875rem',
      fontSizeMax: '0.875rem',
      fluidFontSize: '1.5vw + 0.375rem',
      lineHeightMin: '1.429',
      lineHeightMax: '1.429',
      fluidLineHeight: '1.929em - 1.5vw',
      fontStack: 'body',
      fontWeight: '400',
      textDecoration: 'none',
      fontStyle: 'normal',
    },
    callout2: {
      fontSizeMin: '0.875rem',
      fontSizeMax: '0.875rem',
      fluidFontSize: '1.5vw + 0.375rem',
      lineHeightMin: '1.429',
      lineHeightMax: '1.429',
      fluidLineHeight: '1.929em - 1.5vw',
      fontStack: 'body',
      fontWeight: '600',
      textDecoration: 'none',
      fontStyle: 'normal',
    },
    footnote: {
      fontSizeMin: '0.75rem',
      fontSizeMax: '0.75rem',
      fluidFontSize: '1.5vw + 0.25rem',
      lineHeightMin: '1.5',
      lineHeightMax: '1.5',
      fluidLineHeight: '2em - 1.5vw',
      fontStack: 'body',
      fontWeight: '400',
      textDecoration: 'none',
      fontStyle: 'normal',
    },
    footnote2: {
      fontSizeMin: '0.75rem',
      fontSizeMax: '0.75rem',
      fluidFontSize: '1.5vw + 0.25rem',
      lineHeightMin: '1.5',
      lineHeightMax: '1.5',
      fluidLineHeight: '2em - 1.5vw',
      fontStack: 'body',
      fontWeight: '400',
      textTransform: 'uppercase',
    },
  },

  defaultStylesMapping: {
    h1: 'heading1',
    h2: 'heading2',
    h3: 'heading3',
    h4: 'subtitle',
  },
};
