import { css } from 'styled-components';
import { setProperty } from '../../utils';
import { BoxProps } from './types';

export const injectLayoutHelpers = ({ theme, ...props }: BoxProps & any) =>
  (([
    'all',
    'display',

    'animation',
    'animationDelay',
    'animationDirection',
    'animationDuration',
    'animationFillMode',
    'animationIterationCount',
    'animationName',
    'animationPlayState',
    'animationTimingFunction',

    'appearance',
    'aspectRatio',
    'clipPath',

    'position',
    'top',
    'right',
    'bottom',
    'left',
    'inset',
    'zIndex',

    'opacity',

    'outline',
    'outlineColor',
    'outlineOffset',
    'outlineStyle',

    'overflow',
    'overflowX',
    'overflowY',

    'alignContent',
    'alignSelf',
    'alignItems',
    'justifyContent',
    'justifySelf',
    'placeItems',
    'placeContent',
    'placeSelf',

    'objectFit',
    'objectPosition',

    'padding',
    'paddingVertical',
    'paddingHorizontal',
    'paddingY',
    'paddingX',
    'paddingBlock',
    'paddingBlockStart',
    'paddingBlockEnd',
    'paddingInline',
    'paddingInlineStart',
    'paddingInlineEnd',
    'paddingTop',
    'paddingRight',
    'paddingBottom',
    'paddingLeft',

    'margin',
    'marginVertical',
    'marginHorizontal',
    'marginX',
    'marginY',
    'marginBlock',
    'marginBlockStart',
    'marginBlockEnd',
    'marginInline',
    'marginInlineStart',
    'marginInlineEnd',
    'marginTop',
    'marginRight',
    'marginBottom',
    'marginLeft',
    'marginAuto',

    'accentColor',
    'colorScheme',
    'color',
    'background',
    'backgroundAttachment',
    'backgroundBlendMode',
    'backgroundClip',
    'backgroundColor',
    'backgroundImage',
    'backgroundOrigin',
    'backgroundPosition',
    'backgroundPositionX',
    'backgroundPositionY',
    'backgroundRepeat',
    'backgroundSize',

    'backdropFilter',
    'backdropVisibility',

    'flex',
    'flexGrow',
    'flexShrink',
    'flexBasis',
    'flexWrap',
    'flexFlow',
    'order',
    'gap',

    'width',
    'height',
    'minWidth',
    'minHeight',
    'maxWidth',
    'maxHeight',

    'overflow',
    'overflowX',
    'overflowY',

    'textAlign',
    'textDecoration',
    'textTransform',
    'fontFamily',
    'fontSize',
    'fontStyle',
    'fontStyles',
    'textStyle',
    'fontWeight',

    'boxShadow',
    'textShadow',
    'borderRadius',

    'border',
    'borderBlock',
    'borderBlockColor',
    'borderBlockEnd',
    'borderBlockEndColor',
    'borderBlockEndStyle',
    'borderBlockEndWidth',
    'borderBlockStart',
    'borderBlockStartColor',
    'borderBlockStartStyle',
    'borderBlockStartWidth',
    'borderBlockStyle',
    'borderBlockWidth',
    'borderBottom',
    'borderBottomColor',
    'borderBottomLeftRadius',
    'borderBottomRightRadius',
    'borderBottomStyle',
    'borderBottomWidth',
    'borderCollapse',
    'borderColor',
    'borderEndEndRadius',
    'borderEndStartRadius',
    'borderImage',
    'borderImageOutset',
    'borderImageRepeat',
    'borderImageSlice',
    'borderImageSource',
    'borderImageWidth',
    'borderInline',
    'borderInlineColor',
    'borderInlineEnd',
    'borderInlineEndColor',
    'borderInlineEndStyle',
    'borderInlineEndWidth',
    'borderInlineStart',
    'borderInlineStartColor',
    'borderInlineStartStyle',
    'borderInlineStartWidth',
    'borderInlineStyle',
    'borderInlineWidth',
    'borderLeft',
    'borderLeftColor',
    'borderLeftStyle',
    'borderLeftWidth',
    'borderRadius',
    'borderRight',
    'borderRightColor',
    'borderRightStyle',
    'borderRightWidth',
    'borderSpacing',
    'borderStartEndRadius',
    'borderStartStartRadius',
    'borderStyle',
    'borderTop',
    'borderTopColor',
    'borderTopLeftRadius',
    'borderTopRightRadius',
    'borderTopStyle',
    'borderTopWidth',
    'borderWidth',

    'grid',
    'gridArea',
    'gridColumn',
    'gridRow',
    'gridAutoFlow',
    'gridAutoRows',
    'gridAutoColumns',
    'gridColumnStart',
    'gridColumnEnd',
    'gridRowStart',
    'gridRowEnd',
    'gridTemplateRows',
    'gridTemplateColumns',
    'gridTemplateAreas',

    'transition',
    'transform',

    'whiteSpace',
    'wordBreak',
    'wordWrap',
    'textOverflow',

    'willChange',

    'mask',
    'maskBorder',
    'maskBorderMode',
    'maskBorderOutset',
    'maskBorderRepeat',
    'maskBorderSlice',
    'maskBorderSource',
    'maskBorderWidth',
    'maskClip',
    'maskComposite',
    'maskImage',
    'maskMode',
    'maskOrigin',
    'maskPosition',
    'maskRepeat',
    'maskSize',
    'maskType',

    'cursor',
  ] as const).filter(
    property => props[property] !== undefined,
  ) as string[]).map(property =>
    setProperty({
      property,
      theme,
      value: props[property as keyof BoxProps],
    }),
  );

export const injectVisuallyHiddenHelper = ({ visuallyHidden }: BoxProps) =>
  visuallyHidden &&
  css`
    position: absolute !important;
    border: 0 !important;
    width: 1px !important;
    height: 1px !important;
    padding: 0 !important;
    margin: -1px !important;
    overflow: hidden !important;
    clip: rect(0, 0, 0, 0) !important;
    clip-path: inset(50%) !important;
    white-space: nowrap !important;
    word-wrap: normal !important;
  `;
